# build用Task
# 引用元: https://github.com/tektoncd/website/tree/main/tutorials/katacoda/getting-started
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: task-build-app
spec:
  params:
    - name: dockerfilePath
      type: string
      description: The path to the dockerfile
      default: /workspace/git/tekton-lecture/2/src/Dockerfile
    - name: contextPath
      type: string
      description: Docker build context
      default: /workspace/git/tekton-lecture/2/src/
    - name: imageName
      type: string
      description: The name of built image
      default: app
    - name: gitRepositoryManagerFQDN
      type: string
      description: Repository manager fqdn like github.com or bitbucket.org
      default: github.com
    - name: gitOrganization
      type: string
      description: Github organization
      default: matsubara-ak
    - name: gitRepository
      type: string
      description: Github source code repository
      default: tekton-lecture
    - name: gitRevision
      type: string
      description: The revision/branch of the repository
      default: main
  workspaces:
    - name: git
      description: Mount emptyDir
  steps:
    - name: git-pull
      args:
        - clone
        - https://$(params.gitRepositoryManagerFQDN)/$(params.gitOrganization)/$(params.gitRepository).git
      command:
        - /usr/bin/git
      image: docker:git
      resources: {}
      workingDir: $(workspaces.git.path)
    - name: git-checkout
      args:
        - checkout
        - $(params.gitRevision)
      command:
        - /usr/bin/git
      image: docker:git
      resources: {}
      workingDir: $(workspaces.git.path)/$(params.gitRepository)
    - name: docker
      image: docker
      command:
        - docker
      args:
        - build
        - -f
        - $(params.dockerfilePath)
        - -t
        - $(params.imageName)
        - $(params.contextPath)
      volumeMounts:
        - name: dsocket
          mountPath: /var/run/docker.sock
        - name: dlib
          mountPath: /var/lib/docker
  volumes:
    - name: dsocket
      persistentVolumeClaim:
        claimName: dsocket-vol-claim
    - name: dlib
      persistentVolumeClaim:
        claimName: dlib-vol-claim
