apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline-stg
spec:
  params:
    - name: gitRevision
      type: string
      default: main
  workspaces:
    - name: git
  tasks:
    - name: build-app
      taskRef:
        name: task-build-app
      params:
        - name: gitRevision
          value: $(params.gitRevision)
      workspaces:
        - name: git
          workspace: git
    - name: deploy-app
      taskRef:
        name: task-deploy-app
      runAfter:
        - build-app
