apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: run-pipeline-stg-
spec:
  pipelineRef:
    name: pipeline-stg
  params:
  - name: revision
    value: main
  - name: url
    value: https://github.com/tektoncd/website/
