apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: run-pipeline-stg-
spec:
  params:
    - name: gitRevision
      value: dev
  workspaces:
    - name: git
      emptyDir: {}
  pipelineRef:
    name: pipeline-stg
  timeout: 10m0s
